kufu/renovate-config

- renovate.json
`separateMinorPatch` seems to be required to enable automerge.
> Configuration to apply when an update type is patch. Only applies if separateMinorPatch is set to true
https://docs.renovatebot.com/configuration-options/#patch
> add separateMinorPatch to automerge patch updates

- renovate.json
This PR adds a "renovate" label for all PRs from Renovate.
If you'd like to add another name for the label, you can change like `:label(whatyouwant)`.
docs: https://docs.renovatebot.com/presets-default/#labelltarg0gt
> :sparkles: add a renovate label for a PR

- renovate.json
Currently, this config cannot enable an auto-merge setting for patch versions because it doesn't split `minor` and `patch` version.
https://github.com/renovatebot/config-help/issues/661#issuecomment-630207573
This seems to be caused by not putting `separateMinorPatch: true` in the appropriate place, so I've fixed this.
This PR would change the behavior of Renovate.
If a package's version is `1.0.0`, and has new versions `1.0.1` and `1.1.0`, Renovate would create 2PRs for `1.0.1`(auto-merge) and `1.1.0`(not auto-merge).
> fix: separateMinorPatch should be placed outside pacakgeRules

- renovate.json
styled-components v5.2 includes IE11 white-out bug (https://github.com/styled-components/styled-components/issues/3266), so we MUST NOT use this version.
- set `allowedVersions` of styled-components higher than `5.2`
> prevent updating styled-components v5.2

- renovate.json
[React-PDF v5.0.0 doesn't support IE11.](https://github.com/wojtekmaj/react-pdf/releases/tag/v5.0.0)
> prevent updating React-Pdf to v5.0.0

- renovate.json
styled-components v5.2.0 has IE bug, but as of v5.2.1, it's been fixed.
So, the config for styled-components is no longer needed.
Deleted the config for styled-components.
> remove config for styled-components

- renovate.json
[If you're using husky in a commercial project, you may want to consider becoming a sponsor to support the project. You can also try it for 30 days.](https://github.com/typicode/husky/releases/tag/v5.0.0)
> This is only for a limited time, husky will be MIT again later.
I might be able to unlock this someday...
> chore: prevent updating husky to v5

- renovate.json
fix `html-to-image` version to 0.1.1
ref: https://github.com/kufu/meyasu/pull/936
> chore: fix html-to-image to v0.1.1

- renovate.json
husky's license is back to MIT so want to remove `allowedVersion` of husky.
* remove `allowedVersion` of husky
* c35c82d
* migrate config to newConfig
* a12f4a1
* resolve conflict
* 32813eb
* clone this PR
* run `npx --package renovate -c 'renovate-config-validator'`
* ✅
> remove allowedVersions of husky

- renovate.json
added `":semanticCommitScopeDisabled"` to `extends`
the prefix for pull requests needs to be `chore:` (instead of`chore:(deps)`) when to use [Title Lint](https://github.com/apps/title-lint)
see: https://docs.renovatebot.com/semantic-commits/
> fix: add ":semanticCommitScopeDisabled"

- renovate.json
- スケジューリングは npm に限らないので `schedule` をトップレベルに移動
- `schedule` 設定に `after` 句を追加して、月曜8時〜10時の間に動くように変更
- `packageNames` は `matchPackageNames` にリネームされているので、そのように変更
- https://docs.renovatebot.com/configuration-options/#matchpackagenames
> chore: move `schedule` to the top level

- renovate.json
IE11対応が終了したため、IEのために設定されていたnpm packageのバージョンロックを全て外しました。
> remove allowedVersions for IE

- renovate.json
プロダクト側で `renovate-config` を使っている場合、たまに renovate からの PR が発行されない週があった。
ライブラリの更新は溜め込みたくないため、毎週確実に renovate が実行されるようにしたい。
renovate の実行ログを見ていたところ、renovate のジョブ自体は schedule に関わらず、約3時間おきに実行されているようで、
https://app.renovatebot.com/dashboard#github/kufu
各ジョブ内で、実行時の `timestamp` が `renovate.config` の `schedule` の設定に一致していれば PR を作成するような挙動になっているようだった。
その上で、本日分の従業員サーベイにおける renovate の例を上げると
- 7時台に renovate が実行されるが、schedule の範囲外なのでスキップ
- 10時台後半に renovate が実行されるが、schedule の範囲外なのでスキップ
という動きになっており、どちらも `schedule` の設定の `after 8am before 10am on Monday` に一致していなかったため、本日分の renovate からの PR が作成されていなかった 
上記問題を解決するため、`schedule` の設定を `after 8am before 10am on Monday` から `before 10am on Monday` に変更し、確実に renovate が実行されるようにした。
> chore: renovate が動かない場合があるため、schedule を修正

- renovate.json
表題のとおりです。
`before 10am on Monday` だと深夜帯に slack 通知などが飛ぶ問題があったらしいので、業務時間中に確実に実行されるように変更しました。
> renovate が業務時間中に実行されるように schedule を修正

- renovate.json
rimraf の v4 から glob のサポートがなくなりました。
結果として、`rimraf './.next'` という形式だとこれまでと変わらず削除できますが、`rimraf './.next/**/*.map'` という形式だと削除が行われなくなります。
起こりうる問題として、webpack が吐いたソースマップの削除が行われず、本番環境にソースマップが残ってしまう可能性があります。
なので代替策が見つかるまでは v3 で止めておきます。
> rimraf が v4 にあがらないようにする

- default.json
renovateではデフォルト値として、
- `prHourlyLimit` (1時間あたりに作成できるPR数）: 2
- `prConcurrentLimit` (同時に作成できるPR数）: 10
が設定されています。
（参考：https://docs.renovatebot.com/configuration-options/#prconcurrentlimit）
一方で、`kufu/renovate-config` では `"schedule": "after 8am before 5pm on Monday"` を設定しており、月曜日の日中に、更新が存在するすべてのライブラリのPRが作成されることを期待しているはずです。
ということで、上記2つの制限値を `0` (無制限) に設定し、月曜日に更新があるすべてのライブラリのPRが作成されるように変更しました。
`prHourlyLimit: 0` に関しては従業員サーベイのリポジトリで実験済みで、`prConcurrentLimit` に関しても無制限で良さそうと判断したためそちらも 0 にしています。
> 月曜日に、更新があるすべてのライブラリのPRが作成されるようにする

- default.json
本日のフロント定例で相談した件です（publicリポジトリなので議事録URLの記載はしていません）
limit系の値を無制限にしたことで、CircleCIの同時実行数の制限に引っかかってCIが詰まる事象が発生したため、limit系の数値をデフォルト（未設定）に戻しています。
また、renovateによるPRの作成漏れを防ぐため、scheduleの曜日指定を解除し、毎日PRが作成されるように変更しています。
参考：前回のPR
- https://github.com/kufu/renovate-config/pull/25
> 同時実行数をデフォルトに戻し、毎日renovateのPRが作成されるようにする

- default.json
以前、rimraf が v4 に上がるタイミングで glob のサポートがなくなってしまったため、v4 に上がらないようにしていました。
参考: https://github.com/kufu/renovate-config/pull/21
そして v4.2.0 から glob のサポートが復活したので再びアップデートがされるように、設定を削除しました。
なお、glob サポートを有効にするには `--glob` オプションを付けて実行する必要があるため、プロダクト側での対応が必要になります。
これは別途社内向けに共有しようと思います。
> rimraf のアップデートが行われるようにする

- default.json
Proposal : 休日にrenovateの通知が来て「ビクぅっ！」となるのを防ぎたい気持ちでPRを出します。
真面目な話だと、automergeが設定されてしまっていて、ライブラリがマージされた影響で障害が発生した時に、すぐ対応ができなくなるリスクもあるので、その辺りもリスクヘッジできるかと思います。(本番影響があるものにautomerge設定することはあまりないとは思いますが、予期せず...)
フロントエンドの定例では一応:gogo:もらっております。
マージされたら念の為に frontendメンバには共有しようと思います :bulb:
> chore: 平日のみにrenovateが実行されるように変更

- default.json
ESLint は v9 から flat config がデフォルト化しますが、typescript-eslint を始めとする各種プラグインの対応が出揃わないとバージョンアップするメリットがないため、それまでの間は renovate の対象外とします。
> ESLint は v9 へのバージョンアップの準備ができていないので、当面の間は対象外とする。

- default.json
renovate が以下のような PR を投げることがある。
[chore: update cimg/node docker tag to v22 by renovate[bot] · Pull Request #270 · kufu/stylelint-config-smarthr](https://github.com/kufu/stylelint-config-smarthr/pull/270)
CircleCI で Node の複数バージョンを指定してテストを動かしている(今回の場合は v18 と v20)が、そのどちらも Node のバージョンを v22 にあげてしまっているパターン。
全く同じ環境で同じコマンドを実行するジョブが2つ存在することになってしまいめっちゃ無駄。
これちゃんと PR 見ないと気づかずマージしちゃいがちなので、この PR 自体が発生しないようにしたい。
`cimg/node` の major を `enabled: false` にした
> cimg/node ではメジャーバージョンを自動であげないようにする

- default.json
ua-parser-jsはv2からライセンスがAGPLv3となったため、自動で上がらないように一旦止めておきます
https://github.com/faisalman/ua-parser-js?tab=readme-ov-file#license-options
参考PR：#9
> chore: prevent updating ua-parser-js to v2

- default.json
renovateでは、日々様々な改良が重ねられており、その過程で設定ファイルの更新が必要になる場合があります。
https://docs.renovatebot.com/config-migration/
このPRでは、renovateがconfigのmigrationをするPull Requestを作成してくれる設定を追加します。
* `:configMigration`のpresetをextendした
* https://docs.renovatebot.com/presets-default/#configmigration
* `npx --yes --package renovate -- renovate-config-validator default.json` で、設定を確認済み
> renovateによりconfigMigrationを有効にする

- default.json
> ESLint v9 へのアップデートは可能な状態になっているので enable: false の設定を削除
